import "./globals.css";
import Nav from "./component/nav/Nav";
import Footer from "./component/footer/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="pt-[8rem] bg-white">
          <Nav />
          {children}
          <Footer/>
      </body>
    </html>
  );
}
