import "./globals.css";
import Nav from "./component/nav/Nav";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="pt-32 bg-white">
          <Nav />
          {children}
      </body>
    </html>
  );
}
